#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors");

var one = `
    -------  
   |       |
   |   •   |
   |       |
    -------
`;
var two = `
    ------- 
   | •     |
   |       |
   |     • |
    ------- 
`;

var three = `
    ------- 
   | •     |
   |   •   |
   |     • |
    ------- 
`;
                                                                                                                                                                                                                                   
var four = `
    ------- 
   | •   • |
   |       |
   | •   • |
    -------
`;

var five = `
    ------- 
   | •   • |
   |   •   |
   | •   • |
    ------- 
`;

var six = `
    -------
   | •   • |
   | •   • |
   | •   • |
    -------
`;

var sides = [one, two, three, four, five, six]

function randInt(min,max) {
  return Math.floor((Math.random() * (max - min + 1)) + min);
}

var total = 0
for (var i = 0; i < 5; i++) {
  var side = randInt(0,5);
  console.log(sides[side]);
  total += side;
}

console.log("Total: " + total)
