#!/usr/bin/env python3

import time
import skilstak.colors as c

print(c.clear)

for count in range(3):
    for count in range(12):
        print('Badgers')
        time.sleep(.38)
    for count in range(2):
        print(c.clear)
        print('Mushroom.')
        time.sleep(.5)
        print(c.clear)
    for count in range(11):
        print('Badgers!')
        time.sleep(.38)
    for count in range(2):
        print(c.clear)
        print('Ahh! Its a Snake!')
        time.sleep(.5)
    for count in range(2):
        print('Snake!')
        time.sleep(.5)
        print('Oh its a Snake!')
        time.sleep(.5)
        print(c.clear)
