#!/usr/bin/env python3

import time
import skilstak.colors as c

print(c.clear)

try:
    for count in range(3):
        for count in range(11):
            print(c.multi('Badgers'))
            time.sleep(.38)
        for count in range(2):
            print(c.clear)
            print(c.multi('Mushroom.'))
            time.sleep(.5)
            print(c.clear)
        for count in range(12):
            print(c.multi('Badgers!'))
            time.sleep(.38)
        for count in range(2):
            print(c.clear)
            print(c.multi('Ahh! Its a Snake!'))
            time.sleep(.5)
        for count in range(2):
            print(c.multi('Snake!'))
            time.sleep(.5)
            print(c.multi('Oh its a Snake!'))
            time.sleep(.5)
            print(c.clear)

except:
    pass
