#!/usr/bin/env python3

from random import randrange
import skilstak.colors as c
import time


one     '''  -------               
             |       |
             |   •   |
             |       |
              -------
            ''',

    '''  -------
             | •     |
             |       |
             |     • |
              -------
            ''',

    '''  -------
             | •     |
             |   •   |
             |     • | 
              -------
            ''',

    '''  -------
             | •   • |
             |       |
             | •   • |
              -------
            ''',
 
    '''  -------
             | •   • |
             |   •   |
             | •   • |
              -------
            ''',

    '''  -------
             | •   • |
             | •   • |
             | •   • |
              -------
          '''
]

total = 0

print(c.clear)
for n in range(100):
    rand_int = randrange(1,6)
    print("You rolled a ", rand_int)
    total += rand_int

print("TOTAL: ", total)
