#!/usr/bin/env python3

import random
import skilstak.colors as c
import time

dice = [
    '''  -------               
             |       |
             |   •   |
             |       |
              -------
            ''',

    '''  -------
             | •     |
             |       |
             |     • |
              -------
            ''',

    '''  -------
             | •     |
             |   •   |
             |     • | 
              -------
            ''',

    '''  -------
             | •   • |
             |       |
             | •   • |
              -------
            ''',
 
    '''  -------
             | •   • |
             |   •   |
             | •   • |
              -------
            ''',

    '''  -------
             | •   • |
             | •   • |
             | •   • |
              -------
          '''
]
print(c.clear)
while True:
    question = input(' ')
    print(c.multi(dice))
